[package]
name = "tume"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29"
crossterm = { version = "0.28", features = ["event-stream"] }
anyhow = "1.0"
tui-markdown = "0.3"
ratatui-core = "0.1"
libsql = "0.6"
tokio = { version = "1.42", features = ["full"] }
dirs = "5.0"
